server: 
  port: 8083

#spring:
#  datasource:
#    jdbc-url: jdbc:jtds:sqlserver://localhost/SpringSecurity;sendStringParametersAsUnicode=false
#    username: user
#    password: passw0rd
#    driverClassName: net.sourceforge.jtds.jdbc.Driver
#    connection-test-query: select 1
#    maximum-pool-size: 5
#    minimum-idle: 2
#    pool-name: AccountMgmtPool

spring:
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    connection-test-query: select 1
    maximum-pool-size: 5
    minimum-idle: 2
    pool-name: AccountMgmtPoolH2
    
#enable actuators    
management:
  server:
    port: 9083
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - info
        - metrics

auth:
  issuer-claim-verifier: http://localhost:8081
  auth-server-url: http://localhost:8081/oauth-server/oauth
  client-id: fbm-user
  client-secret: secret-fbm
  jwt-public-key-filename: public.txt
  
logging:
  file: c:/logs/@project.name@.log
  level:
    root: INFO 
    org:
      springframework:
        security: INFO
        web: INFO
      hibernate: INFO
      
#debug: true
 